# This is a Github Workflow that runs tests on any push or pull request.
# If the tests pass and this is a push to the master branch it also runs Semantic Release.
name: CI
on: [push, pull_request]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Use Node.js 24
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            target
            package.json
            package-main.json
            jsr.json
          retention-days: 1

  test:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'
      - uses: actions/download-artifact@v5
        with:
          name: build
      - name: Fetch deps
        run: npm ci
      - name: Run tests
        run: npm run test
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            target/coverage
            package.json
          retention-days: 1

  release:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      checks: read
      statuses: write
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/download-artifact@v5
        with:
          merge-multiple: true
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'
      - name: Semantic Release
        if: github.ref == 'refs/heads/main'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_PROVENANCE: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USER: 'x-access-token'
          GIT_BRANCH: 'main'
          GIT_AUTHOR_NAME: ${{ vars.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ vars.GIT_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ vars.GIT_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ vars.GIT_COMMITTER_EMAIL }}
        run: npx zx-semrel

      - name: Push docs and coverage
        env:
          GIT_COMMITTER_NAME: ${{ vars.GIT_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ vars.GIT_COMMITTER_EMAIL }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          GH_SHA: ${{ github.sha }}
        run: |
          npm run publish:docs
          npm run publish:coverage

  pr:
    if: github.event_name == 'pull_request'
    needs: build
    name: pr-os-${{ matrix.os }}-nodejs-${{ matrix.node-version }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        node-version: [ 6, 12, 18, 20, 22, 24, 25-nightly ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - uses: actions/download-artifact@v5
        with:
          name: build

      - name: Run all tests
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == 20
        run: |
          npm ci
          npm run test
      - name: Run spawn tests (win32)
        if: matrix.os == 'windows-latest' && matrix.node-version == 20
        run: |
          npm ci
          node --loader ts-node/esm --experimental-specifier-resolution=node ./src/test/ts/spawn.test.ts
        timeout-minutes: 5

      - name: Run smoke:esm tests
        if: matrix.node-version >= 12
        run: npm run test:smoke:esm

      - name: Run smoke:cjs tests
        run: npm run test:smoke:cjs

  smoke-bun:
    if: github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Bun
        uses: antongolub/action-setup-bun@f0b9f339a7ce9ba1174a58484e4dc9bbd6f7b133 # v1.13.2
      - uses: actions/download-artifact@v5
        with:
          name: build
      - run: |
          bun ./src/test/smoke/invoke.test.cjs
          bun ./src/test/smoke/invoke.test.mjs

  smoke-deno:
    needs: build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: smoke-deno-${{ matrix.deno-version }}
    strategy:
      matrix:
        deno-version: [ 1, 2 ]
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Deno
        uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755 # v2.0.2
        with:
          deno-version: ${{ matrix.deno-version }}
      - run: deno install npm:types/node
      - uses: actions/download-artifact@v5
        with:
          name: build
      - run: deno test --allow-read --allow-sys --allow-env --allow-run ./src/test/smoke/invoke.test.mjs
